<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="7" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="190" started-at="2018-06-28T08:19:57Z" finished-at="2018-06-28T08:19:57Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="190" started-at="2018-06-28T08:19:57Z" finished-at="2018-06-28T08:19:57Z">
      <class name="com.qait.automation.SnlMaven.SnlTest1">
        <test-method status="PASS" signature="launchwindow()[pri:0, instance:com.qait.automation.SnlMaven.SnlTest1@573f2bb1]" name="launchwindow" is-config="true" duration-ms="28" started-at="2018-06-28T13:49:57Z" finished-at="2018-06-28T13:49:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchwindow -->
        <test-method status="PASS" signature="try_adding_same_name_user()[pri:0, instance:com.qait.automation.SnlMaven.SnlTest1@573f2bb1]" name="try_adding_same_name_user" duration-ms="14" started-at="2018-06-28T13:49:57Z" finished-at="2018-06-28T13:49:57Z">
          <exception class="com.qait.automation.SnlMaven.PlayerExistsException">
            <message>
              <![CDATA[Player 'Player1' already exists on board]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qait.automation.SnlMaven.PlayerExistsException: Player 'Player1' already exists on board
	at com.qait.automation.SnlMaven.Board.registerPlayer(Board.java:74)
	at com.qait.automation.SnlMaven.SnlTest1.try_adding_same_name_user(SnlTest1.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.qait.automation.SnlMaven.PlayerExistsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- try_adding_same_name_user -->
        <test-method status="PASS" signature="launchwindow()[pri:0, instance:com.qait.automation.SnlMaven.SnlTest1@573f2bb1]" name="launchwindow" is-config="true" duration-ms="7" started-at="2018-06-28T13:49:57Z" finished-at="2018-06-28T13:49:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchwindow -->
        <test-method status="PASS" signature="try_adding_user_when_gamestarted()[pri:0, instance:com.qait.automation.SnlMaven.SnlTest1@573f2bb1]" name="try_adding_user_when_gamestarted" duration-ms="23" started-at="2018-06-28T13:49:57Z" finished-at="2018-06-28T13:49:57Z">
          <exception class="com.qait.automation.SnlMaven.GameInProgressException">
            <message>
              <![CDATA[New player cannot join since the game has started]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qait.automation.SnlMaven.GameInProgressException: New player cannot join since the game has started
	at com.qait.automation.SnlMaven.Board.registerPlayer(Board.java:77)
	at com.qait.automation.SnlMaven.SnlTest1.try_adding_user_when_gamestarted(SnlTest1.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.qait.automation.SnlMaven.GameInProgressException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- try_adding_user_when_gamestarted -->
        <test-method status="PASS" signature="launchwindow()[pri:0, instance:com.qait.automation.SnlMaven.SnlTest1@573f2bb1]" name="launchwindow" is-config="true" duration-ms="7" started-at="2018-06-28T13:49:57Z" finished-at="2018-06-28T13:49:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchwindow -->
        <test-method status="PASS" signature="try_deleting_user()[pri:0, instance:com.qait.automation.SnlMaven.SnlTest1@573f2bb1]" name="try_deleting_user" duration-ms="21" started-at="2018-06-28T13:49:57Z" finished-at="2018-06-28T13:49:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- try_deleting_user -->
        <test-method status="PASS" signature="launchwindow()[pri:0, instance:com.qait.automation.SnlMaven.SnlTest1@573f2bb1]" name="launchwindow" is-config="true" duration-ms="5" started-at="2018-06-28T13:49:57Z" finished-at="2018-06-28T13:49:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchwindow -->
        <test-method status="PASS" signature="try_deleting_user_already_deleted()[pri:0, instance:com.qait.automation.SnlMaven.SnlTest1@573f2bb1]" name="try_deleting_user_already_deleted" duration-ms="6" started-at="2018-06-28T13:49:57Z" finished-at="2018-06-28T13:49:57Z">
          <exception class="com.qait.automation.SnlMaven.NoUserWithSuchUUIDException">
            <message>
              <![CDATA[No Player with uuid '483dc87f-24a5-488f-813b-062aaa68dbff' on board]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qait.automation.SnlMaven.NoUserWithSuchUUIDException: No Player with uuid '483dc87f-24a5-488f-813b-062aaa68dbff' on board
	at com.qait.automation.SnlMaven.Board.deletePlayer(Board.java:112)
	at com.qait.automation.SnlMaven.SnlTest1.try_deleting_user_already_deleted(SnlTest1.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.qait.automation.SnlMaven.NoUserWithSuchUUIDException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- try_deleting_user_already_deleted -->
        <test-method status="PASS" signature="launchwindow()[pri:0, instance:com.qait.automation.SnlMaven.SnlTest1@573f2bb1]" name="launchwindow" is-config="true" duration-ms="4" started-at="2018-06-28T13:49:57Z" finished-at="2018-06-28T13:49:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchwindow -->
        <test-method status="PASS" signature="try_deleting_user_not_registered_on_board()[pri:0, instance:com.qait.automation.SnlMaven.SnlTest1@573f2bb1]" name="try_deleting_user_not_registered_on_board" duration-ms="1" started-at="2018-06-28T13:49:57Z" finished-at="2018-06-28T13:49:57Z">
          <exception class="com.qait.automation.SnlMaven.NoUserWithSuchUUIDException">
            <message>
              <![CDATA[No Player with uuid '01385e65-9717-4a97-84ef-e246793f339e' on board]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qait.automation.SnlMaven.NoUserWithSuchUUIDException: No Player with uuid '01385e65-9717-4a97-84ef-e246793f339e' on board
	at com.qait.automation.SnlMaven.Board.deletePlayer(Board.java:112)
	at com.qait.automation.SnlMaven.SnlTest1.try_deleting_user_not_registered_on_board(SnlTest1.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.qait.automation.SnlMaven.NoUserWithSuchUUIDException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- try_deleting_user_not_registered_on_board -->
        <test-method status="PASS" signature="launchwindow()[pri:0, instance:com.qait.automation.SnlMaven.SnlTest1@573f2bb1]" name="launchwindow" is-config="true" duration-ms="4" started-at="2018-06-28T13:49:57Z" finished-at="2018-06-28T13:49:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchwindow -->
        <test-method status="PASS" signature="try_making_invalid_turn()[pri:0, instance:com.qait.automation.SnlMaven.SnlTest1@573f2bb1]" name="try_making_invalid_turn" duration-ms="9" started-at="2018-06-28T13:49:57Z" finished-at="2018-06-28T13:49:57Z">
          <exception class="com.qait.automation.SnlMaven.InvalidTurnException">
            <message>
              <![CDATA[Player 'b317bbd4-928e-4690-8877-853b202c7cbf' does not have the turn]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qait.automation.SnlMaven.InvalidTurnException: Player 'b317bbd4-928e-4690-8877-853b202c7cbf' does not have the turn
	at com.qait.automation.SnlMaven.Board.rollDice(Board.java:166)
	at com.qait.automation.SnlMaven.SnlTest1.try_making_invalid_turn(SnlTest1.java:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.qait.automation.SnlMaven.InvalidTurnException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- try_making_invalid_turn -->
        <test-method status="PASS" signature="launchwindow()[pri:0, instance:com.qait.automation.SnlMaven.SnlTest1@573f2bb1]" name="launchwindow" is-config="true" duration-ms="3" started-at="2018-06-28T13:49:57Z" finished-at="2018-06-28T13:49:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchwindow -->
        <test-method status="PASS" signature="trying_to_add_more_than_four_players()[pri:0, instance:com.qait.automation.SnlMaven.SnlTest1@573f2bb1]" name="trying_to_add_more_than_four_players" duration-ms="11" started-at="2018-06-28T13:49:57Z" finished-at="2018-06-28T13:49:57Z">
          <exception class="com.qait.automation.SnlMaven.MaxPlayersReachedExeption">
            <message>
              <![CDATA[The board already has maximum allowed Player: 4]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qait.automation.SnlMaven.MaxPlayersReachedExeption: The board already has maximum allowed Player: 4
	at com.qait.automation.SnlMaven.Board.registerPlayer(Board.java:69)
	at com.qait.automation.SnlMaven.SnlTest1.trying_to_add_more_than_four_players(SnlTest1.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.qait.automation.SnlMaven.MaxPlayersReachedExeption -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- trying_to_add_more_than_four_players -->
      </class> <!-- com.qait.automation.SnlMaven.SnlTest1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
